### ISSUE TITLE
Not working on Nox Emulator

### ISSUE THREAD

**Issue by IQDevloper** [Eltion/Snapchat-SSL-Pinning-Bypass#1]
i patched the App successfuly and run Burp and then run Snap app with Frida but i'm geting error no connection at all !!

![Screenshot_2](https://user-images.githubusercontent.com/104209805/210163546-d45f758a-15c3-49be-b54b-4cfd2672013a.png)

**Comment by Eltion** [comment]
@IQDevloper I notice you're using an emulator, this patch will only work on real device with arm, arm64 architecture.

I think there is possible to make it also work on Nox Emulator, I did something similar for tiktok. 
You can follow that here:
https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/issues/2

**Comment by liemvt2008** [comment]
Hello @Eltion
I'm quite new on this.
I'm trying to follow your instruction and use a real device for install and login with your **Patched APK** uploaded. 
As you mentioned that 
> this patch will only work on real device with arm, arm64 architecture.

However, it's still got error as image show.
![snapchat](https://user-images.githubusercontent.com/11953899/210735118-711afd6b-6d21-4d5a-81f8-0a77a4d7ccde.jpg)

Please give me some suggestion to overcome this error.
Many thanks

**Comment by Eltion** [comment]
@liemvt2008 thanks for reporting that. Do you mind telling me if your phone is arm, or arm64. I'm only able to test the arm64 version, so there may be a problem with the arm version.

**Comment by liemvt2008** [comment]
@Eltion, thank you for your replies.
As I checked via command 
> adb shell getprop ro.product.cpu.abi
armeabi-v7a

The result is armeabi-v7a and via some searching
`https://stackoverflow.com/a/48340077` I found that my arm is 32bit. 
Do we have any way to make this work on my phone? Please give me some advice. 
Many thanks.

**Comment by Eltion** [comment]
@liemvt2008 , I will soon sent you a version and maybe you can test it and let me know if it works

**Comment by Eltion** [comment]
@liemvt2008, can you test if this works for you, 
https://send.vis.ee/download/eb6366584275f0a9/#yJIi6PAjhdkaBUugtavQJg

**Comment by Eltion** [comment]
@liemvt2008, if that is not working, try this:
https://send.vis.ee/download/a345f2a8a42f213f/#lvG59TV52kmcJ8jkNSsA4A

**Comment by liemvt2008** [comment]
@Eltion ,

* Many thanks for your support. However, for your first version. It's still not working and blocked me as error code C14A

* With the second app_patched, I got this error while trying to install it to my phone

> adb install app_patched.apk
Performing Streamed Install
adb: failed to install app_patched.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl935943506.tmp/base.apk]

I guest that something happened while compiling the base.apk after update.
Once again, I'm very appreciate your helping and grateful support.
Please help me. I lost many months to struggle and try many way with this app.

**Comment by Eltion** [comment]
@liemvt2008  can you try this one:
https://send.vis.ee/download/650edacbfd27a59f/#V_3XKuTmM30fCx_KkOC0Zw

Remember to uninstall snpachat before installing this

**Comment by liemvt2008** [comment]
Hello @Eltion ,

I've tried your new app_patched but the result still the same.
![snapchat_v2](https://user-images.githubusercontent.com/11953899/211257213-73989694-3ec5-4ad1-b48e-b4419fa6edd1.jpg)
Maybe I will find some devices which use arm64-v8a but I'm not sure how long does it take.
Please help me with armeabi-v7a structure while I'm moving around and finding new devices.
Many thanks for your time and your effort to support me.

**Comment by liemvt2008** [comment]
Hello @Eltion,

As you mentioned before, I found another devices which using arm64 

> adb shell getprop ro.product.cpu.abi
arm64-v8a

This device totally new to Snapchat and I downloaded your release package as version `snapchat-v12.08.0.29.apk` 
However, the Snapchat still ask me for error C14A as below
![snapchat_v64](https://user-images.githubusercontent.com/11953899/211290320-c12c3fc8-95c8-485f-a30d-4f6d23a577d9.jpg)
I'm trying my best and find any solution so I can to bypass this app pinning.
Please give me more advice or suggestion if you have. 
Many thanks for your support.

**Comment by Eltion** [comment]
@liemvt2008, seems like snapchat is detecting that apk is patched. there was a new issue open for this. You can follow up here:
https://github.com/Eltion/Snapchat-SSL-Pinning-Bypass/issues/2

**Comment by Eltion** [comment]
@liemvt2008 both the problems should be solved now. I've created a new release here:
https://github.com/Eltion/Snapchat-SSL-Pinning-Bypass/releases/tag/v12.16.0.28

Let me know if it's working.

**Comment by liemvt2008** [comment]
Hello @Eltion ,

This was awesome. Everything is working like magic. 
![Screenshot from 2023-01-10 14-29-33](https://user-images.githubusercontent.com/11953899/211489086-7f1ba6e7-6350-4033-9895-01330e07b702.png)

Thank you very very much for your effort and time to bypass this app.

**Comment by IQDevloper** [comment]
Hi Guys, I still see the same error message, "Something went wrong...," when using the Nox player emulator (x86 64).
Could help me with this ?
 I would appreciate it.

**Comment by Eltion** [comment]
@IQDevloper yes also the new release won't work with Nox emulator. The only way to achieve that is to do a patch without using firda.

**Comment by IQDevloper** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/104209805/211826434-01d49817-4bde-4a6d-877b-01952c322c92.png)

i still get the same error i tried with Burp and Http toolkit ( i'm using Nox Player ' Android 9 ' )
why do you think is not working with me ?

**Comment by Eltion** [comment]
No it won't work using frida-server. You need to install the apk I've sent don't need to run frida. Also the patch is made for x86 so Nox 'Android 9' is 64bit. I've tested it in Nox Android 7

**Comment by IQDevloper** [comment]
> 

Thank you for your quick reply. I just installed the patched version on NoxPlayer 7 x86, ran Http Toolkit on it, and still get the same error !?

**Comment by IQDevloper** [comment]
01-12 00:49:35.958 10496 10496 V SNAPCHAT_SSL_PINNING_BYPASS: [*][+] Hooked checkTrustedRecursive
01-12 00:49:36.235 10496 10496 V SNAPCHAT_SSL_PINNING_BYPASS: [*][+] Hooked SSLContextInit

> Can you do the following and sent the output:
> 
> ```
> cd C:\Program Files\Nox\bin\
> .\adb.exe logcat -c
> .\adb.exe logcat -s "SNAPCHAT_SSL_PINNING_BYPASS:V"
> ```

please read my comment above i edited it, the app works but when i run any Intercept app it's not and the requests abort

**Comment by IQDevloper** [comment]
Yes, i'm sure, but why is not working when i run Http Toolkit with notes Instagram works with it prefictly even Burp and i installed certificate !

Could please help me with that ?

**Comment by Eltion** [comment]
@IQDevloper can you try mitmproxy ?

**Comment by Eltion** [comment]
@IQDevloper  I can confirm that it's not working on Burp or Http Toolkit

**Comment by alijafari96** [comment]
Hi. I've used the last released apk you put here but I got the below error

![image](https://user-images.githubusercontent.com/20299989/211913568-71122920-74ab-4c23-bcef-4bb88719a225.png)

**Comment by Eltion** [comment]
@alijafari96 Can you tell me what architecture is your phone, and what proxy tool are you using

**Comment by admin22312** [comment]
> @alijafari96 Can you tell me what architecture is your phone, and what proxy tool are you using

Those requests that we see for snapchat, is it possible to process for personal use? Or maybe you encountered some problems when trying to substitute other data for such requests?
In any case, thank you for the information, but it will be valuable to know if you have tried or maybe know that this can be successfully implemented for further work with them

**Comment by alijafari96** [comment]
> @alijafari96 Can you tell me what architecture is your phone, and what proxy tool are you using

My phone architecture is ARMv8.2-A and I use Burp to intercept the traffic.

**Comment by Eltion** [comment]
@alijafari96 can you try with mitmproxy

**Comment by Eltion** [comment]
Considering this issue as resolved.

**Comment by alijafari96** [comment]
> @alijafari96 can you try with mitmproxy

Hi @Eltion, Sorry for late response.
Yes, It works when I use mitmproxy instead of burp. But I can't understand why burp does not work.
I even enabled invisible-proxy in burp settings but that didn't solve the problem.
Is there any way that I can intercept traffic using burp and not mitmproxy? Why does mitmproxy works and burp doesn't?

Do you have any idea? @Eltion 
Tnx for your responses and time Eltion

**Comment by itzelliotto** [comment]
Hi @Eltion, 
How do I use mitmproxy? do I need to run any code on command prompt after installing the nox version and the mitmproxy?
(I'm not a coder, but I can copy code in cmd prompt)

**Comment by itzelliotto** [comment]
Didn't work for me

![Screenshot (529)](https://github.com/Eltion/Snapchat-SSL-Pinning-Bypass/assets/86394600/a61519d6-41cc-4139-8602-6d912d1af667)


> Hi @Eltion, How do I use mitmproxy? do I need to run any code on command prompt after installing the nox version and the mitmproxy? (I'm not a coder, but I can copy code in cmd prompt)

**Comment by sosixhamee136-byte** [comment]
vous avez une IPA pour contourner le ban ss06 et ss03 svp?
